# Generated by Django 6.0.3 on 2026-03-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='alerta_estoque_minimo',
            field=models.IntegerField(default=10),
        ),
    ]
