# Generated by Django 6.0.3 on 2026-03-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='nome',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
        ),
    ]
