# Generated by Django 6.0.3 on 2026-03-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movimentacaoestoque_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='telefone',
        ),
        migrations.AddField(
            model_name='entregador',
            name='nome',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregador',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entregador'),
        ),
    ]
