# Generated by Django 6.0.3 on 2026-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_movimentacaoestoque_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20),
        ),
    ]
