# Generated by Django 6.0.3 on 2026-03-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_venda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contatado_hoje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacao_comercial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_contato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
