# Generated by Django 6.0.3 on 2026-03-17 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_contatado_hoje_cliente_observacao_comercial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('combustivel', 'Combustível'), ('alimentacao', 'Alimentação'), ('manutencao', 'Manutenção'), ('compra_estoque', 'Compra de estoque'), ('conta', 'Conta fixa'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
        ),
    ]
