# Generated by Django 6.0.3 on 2026-03-17 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retiradafuncionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CompraEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('quantidade', models.IntegerField()),
                ('custo_unitario_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
