# Generated by Django 6.0.3 on 2026-03-17 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contapagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_retiradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dinheiro_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pix_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credito_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debito_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dinheiro_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pix_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credito_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debito_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
                'unique_together': {('loja', 'data')},
            },
        ),
    ]
