# Generated by Django 6.0.3 on 2026-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fechamentocaixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento_1',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito')], default='dinheiro', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento_2',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pagamento_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pagamento_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
