# Generated by Django 6.0.3 on 2026-03-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_venda_forma_pagamento_venda_forma_pagamento_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='controla_retorno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('normal', 'Venda normal'), ('troca', 'Troca com devolução'), ('completo', 'Venda completa sem devolução'), ('casco', 'Venda só do casco')], default='normal', max_length=20),
        ),
    ]
