# Generated by Django 6.0.3 on 2026-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_produto_controla_retorno_venda_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('gerente', 'Gerente'), ('admin', 'Admin')], default='funcionario', max_length=20),
        ),
    ]
