# Generated by Django 6.0.3 on 2026-03-19 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_compraestoque_aprovado_em_compraestoque_aprovado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='compraestoque',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['status', 'vencimento']},
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='entregador',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-data_movimentacao']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_pedido']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='retiradafuncionario',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda']},
        ),
        migrations.RenameField(
            model_name='contapagar',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entregador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='categoria',
            field=models.CharField(choices=[('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('fornecedor', 'Fornecedor'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('combustivel', 'Combustível'), ('alimentacao', 'Alimentação'), ('manutencao', 'Manutenção'), ('compra_estoque', 'Compra de estoque'), ('conta', 'Conta fixa'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loja'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste_cheio', 'Ajuste estoque cheio'), ('ajuste_vazio', 'Ajuste estoque vazio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito')], default='dinheiro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loja'),
        ),
        migrations.AlterField(
            model_name='retiradafuncionario',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiradas_recebidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
