# Generated by Django 6.0.3 on 2026-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cliente_options_alter_compraestoque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraestoque',
            name='tipo_compra',
            field=models.CharField(choices=[('troca', 'Troca de vazio por cheio'), ('somente_cheio', 'Somente entrada de cheio')], default='troca', max_length=20),
        ),
    ]
