# Generated by Django 6.0.3 on 2026-03-19 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_fechamentocaixa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriasistema',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='fechamentocaixa',
            options={'ordering': ['-data', '-criado_em']},
        ),
        migrations.AlterUniqueTogether(
            name='fechamentocaixa',
            unique_together={('loja', 'data')},
        ),
        migrations.AddField(
            model_name='auditoriasistema',
            name='acao',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditoriasistema',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auditoriasistema',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='data',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='InventarioEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventarioEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_cheio_sistema', models.IntegerField(default=0)),
                ('estoque_vazio_sistema', models.IntegerField(default=0)),
                ('estoque_cheio_contado', models.IntegerField(default=0)),
                ('estoque_vazio_contado', models.IntegerField(default=0)),
                ('diferenca_cheio', models.IntegerField(default=0)),
                ('diferenca_vazio', models.IntegerField(default=0)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.inventarioestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='descricao',
        ),
    ]
