# Generated by Django 6.0.3 on 2026-03-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='telefone',
        ),
        migrations.AddField(
            model_name='loja',
            name='cidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='loja',
            name='tempo_entrega_max',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='loja',
            name='tempo_entrega_min',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
