# Generated by Django 6.0.3 on 2026-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_loja_telefone_loja_cidade_loja_taxa_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='horario_abertura',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='loja',
            name='horario_fechamento',
            field=models.TimeField(default='19:00'),
        ),
    ]
