# Generated by Django 6.0.3 on 2026-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_loja_horario_abertura_loja_horario_fechamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_desconto', models.CharField(choices=[('valor', 'Valor fixo'), ('percentual', 'Percentual')], default='valor', max_length=20)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('uso_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('total_usado', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
