# Generated by Django 6.0.3 on 2026-04-05 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cliente_bairro_cliente_cidade_cliente_complemento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='comissao_percentual',
        ),
        migrations.AddField(
            model_name='entregador',
            name='recebe_frete',
            field=models.BooleanField(default=False, help_text='Marque se recebe frete fixo por entrega.'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Conta de login para acessar o Painel do Entregador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregador',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo por entrega realizada (somente se recebe_frete estiver marcado).', max_digits=10),
        ),
        migrations.AddField(
            model_name='loja',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desativar impede acesso sem excluir a loja.'),
        ),
        migrations.AddField(
            model_name='loja',
            name='loja_principal',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco se esta é uma loja principal. Selecione a principal se esta é uma filial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais', to='core.loja'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='perfilusuario',
            unique_together={('user', 'loja')},
        ),
    ]
