"""
Django settings for gaserp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os

SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    'core',
    'pedidos',
    'maquina',
]

JAZZMIN_SETTINGS = {
    "site_title": "VillaGás Admin",
    "site_header": "VillaGás",
    "site_brand": "VillaGás",
    "welcome_sign": "Bem-vindo ao sistema VillaGás",
    "copyright": "VillaGás © 2026",
    "site_logo": None,
    "site_icon": None,
    "search_model": ["core.cliente", "core.produto", "core.pedido"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Sistema", "url": "https://admin.villagaz.com.br", "new_window": False},
        {"model": "core.pedido"},
        {"model": "core.venda"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "core.loja", "core.produto", "auth.user", "core.perfilusuario",
        "core.entregador", "core.cliente", "core.fornecedor",
        "core.venda", "core.pedido", "core.vendaantecipada",
        "core.compraestoque", "core.movimentacaoestoque", "core.inventarioestoque",
        "core.fechamentocaixa", "core.despesa", "core.retiradafuncionario",
        "core.contapagar", "core.comissao", "core.meta_vendas",
        "core.comodato", "core.cupomdesconto",
        "core.veiculo", "core.abastecimentoveiculo", "core.manutencaoveiculo",
        "core.checklistveiculo", "core.rotaentrega", "core.veiculorota",
        "core.auditoriasistema", "core.notificacaosistema",
        "core.valegas", "core.metricaentregador",
    ],
    "icons": {
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "core.loja": "fas fa-store",
        "core.produto": "fas fa-box",
        "core.perfilusuario": "fas fa-id-badge",
        "core.entregador": "fas fa-truck",
        "core.cliente": "fas fa-user-tag",
        "core.fornecedor": "fas fa-industry",
        "core.venda": "fas fa-cash-register",
        "core.pedido": "fas fa-clipboard-list",
        "core.vendaantecipada": "fas fa-calendar-check",
        "core.compraestoque": "fas fa-dolly",
        "core.movimentacaoestoque": "fas fa-exchange-alt",
        "core.inventarioestoque": "fas fa-warehouse",
        "core.iteminventarioestoque": "fas fa-list-ol",
        "core.fechamentocaixa": "fas fa-cash-register",
        "core.despesa": "fas fa-receipt",
        "core.retiradafuncionario": "fas fa-hand-holding-usd",
        "core.contapagar": "fas fa-file-invoice-dollar",
        "core.contareceber": "fas fa-file-invoice",
        "core.comissao": "fas fa-percentage",
        "core.meta_vendas": "fas fa-bullseye",
        "core.comodato": "fas fa-recycle",
        "core.cupomdesconto": "fas fa-tag",
        "core.veiculo": "fas fa-car",
        "core.abastecimentoveiculo": "fas fa-gas-pump",
        "core.manutencaoveiculo": "fas fa-tools",
        "core.checklistveiculo": "fas fa-clipboard-check",
        "core.alertamanutencao": "fas fa-bell",
        "core.rotaentrega": "fas fa-route",
        "core.veiculorota": "fas fa-map-marked-alt",
        "core.auditoriasistema": "fas fa-search",
        "core.notificacaosistema": "fas fa-bell",
        "core.valegas": "fas fa-ticket-alt",
        "core.metricaentregador": "fas fa-chart-bar",
        "pedidos.pedido": "fas fa-clipboard-list",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-orange",
    "accent": "accent-orange",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-orange",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gaserp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.perfil_ativo',
            ],
        },
    },
]

WSGI_APPLICATION = 'gaserp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = '/var/www/villagas/static'
MEDIA_ROOT = '/var/www/villagas/media'


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'https://villagaz.com.br',
    'https://www.villagaz.com.br',
    'https://admin.villagaz.com.br',
    'https://villagas-7wv23nbx7-butzps147-1591s-projects.vercel.app',
]


CSRF_TRUSTED_ORIGINS = [
    'https://villagaz.com.br',
    'https://www.villagaz.com.br',
    'https://admin.villagaz.com.br',
    'https://villagas-7wv23nbx7-butzps147-1591s-projects.vercel.app',
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    },
}
