# Generated by Django 6.0.3 on 2026-04-20 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0038_produto_preco_gas_do_povo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Maquina GLP - Patio Principal', max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('preco_troca', models.DecimalField(decimal_places=2, default=0, help_text='Preco com devolucao do vasilhame', max_digits=10)),
                ('preco_avulso', models.DecimalField(decimal_places=2, default=0, help_text='Preco sem devolucao do vasilhame', max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=2, help_text='Alerta quando atingir este nivel')),
                ('versao_firmware', models.CharField(blank=True, max_length=20)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='core.loja')),
                ('produto', models.ForeignKey(help_text='Produto P13 que esta maquina vende', on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='core.produto')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alarme_gas', 'Alarme de Gás'), ('abertura_nao_autorizada', 'Abertura Não Autorizada'), ('estoque_baixo', 'Estoque Baixo'), ('falha_sensor', 'Falha de Sensor'), ('falha_pagamento', 'Falha de Pagamento'), ('queda_energia', 'Queda de Energia'), ('reconexao', 'Reconexão'), ('manutencao', 'Manutenção'), ('info', 'Informativo'), ('erro', 'Erro')], max_length=30)),
                ('severidade', models.CharField(choices=[('critico', 'Crítico'), ('aviso', 'Aviso'), ('info', 'Info')], default='info', max_length=10)),
                ('mensagem', models.TextField()),
                ('dados_extras', models.JSONField(blank=True, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='maquina.maquina')),
            ],
            options={
                'verbose_name': 'Evento da Máquina',
                'verbose_name_plural': 'Eventos da Máquina',
                'ordering': ['-criado_em'],
            },
        ),
    ]
