# Generated by Django 6.0.3 on 2026-04-20 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venda', models.CharField(max_length=10)),
                ('forma_pagamento', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('pago', 'Pago'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='aguardando', max_length=12)),
                ('stone_order_id', models.CharField(blank=True, max_length=100)),
                ('stone_qr_code', models.TextField(blank=True)),
                ('stone_qr_code_url', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='maquina.maquina')),
            ],
            options={
                'verbose_name': 'Pagamento Pendente',
                'verbose_name_plural': 'Pagamentos Pendentes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
